M48
; DRILL file {KiCad (6.0.7)} date Mon Sep  5 17:33:01 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-05T17:33:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X5.9Y-5.0933
T2
X5.9Y-5.3867
T3
X4.7482Y-3.7982
X6.2718Y-3.7982
T4
X4.53Y-3.58
X4.53Y-5.57
X7.37Y-3.58
X7.37Y-5.57
T0
M30
